### ISSUE TITLE
Parrot failing to find Cython 

### ISSUE THREAD

**Issue by jlotthammer** [idptools/parrot#10]
It seems that we have an issue with Parrot finding cython. Here are the details I was able to gather. 

Error message:
warning in stationary: failed to import cython module: falling back to numpy 
warning in coregionalize: failed to import cython module: falling back to numpy 
warning in choleskies: failed to import cython module: falling back to numpy

Version information: 
Python 3.7.6
parrot.__version__   = 'v1.6.2+0.gd17a873.dirty'
Cython.__version__ =  0.29.24

OS:
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.3 LTS
Release:        20.04
Codename:       focal

cc: @degriffith @alexholehouse we should try to look into these and resolve, I'd be interested to know if you guys also have the same issues - it appears that ryan does as well.

**Comment by degriffith** [comment]
I've seen this before, a while back. If I remember correctly this is a GPy version vs Python version issue

**Comment by jlotthammer** [comment]
FWIW in case there was any doubt, this  **_is_** an issue with Gpy, because the detachment of `parrot-optimize` from PyPI does prohibit this numpy fallback from happening.
