### ISSUE TITLE
module 'numpy' has no attribute 'bool'.

### ISSUE THREAD

**Issue by jourmore** [idptools/parrot#12]
module 'numpy' has no attribute 'bool'.
`np.bool` was a deprecated alias for the builtin `bool`. To avoid this error in existing code, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

**Comment by alexholehouse** [comment]
I don't disagree, and it's totally possible we have this issue in the codebase, but a quick search of the src does not find any hits for np.bool; could you maybe elaborate on where this occurs and how it emerged as an issue in your work?

**Comment by jlotthammer** [comment]
feel free to reopen with more information if you're still facing issues
